[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  PUPPETEER_SKIP_DOWNLOAD = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
